name: Deploy to render
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    name: Deploy on render
    runs-on: ubuntu-latest
    steps:
      - name: Call hook
        run:
          curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
